openapi: 3.0.1
info:
  title: ' '
  version: 1.0.0
servers:
- url: /
paths:
  /hello:
    get:
      operationId: operation1_get_/hello
      responses:
        "200":
          description: Successful
          content:
            text/plain:
              schema:
                type: string
  /ping:
    post:
      operationId: operation1_post_/ping
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
  /authorise:
    post:
      operationId: operation1_post_/authorise
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
components: {}
